#!/bin/bash

configfile=/home/pi/scripts/config.cfg
if [ -f $configfile ]; then
  source $configfile
fi

if ! [[ $(lsusb | grep -i 'Mouse'| tr "A-Z" "a-z") = *mouse* ]]; then
  echo "doesnt exist"
	if grep -q "#xserver-command=X -nocursor" /etc/lightdm/lightdm.conf; then
    echo "removed"
    if [[ $MouseIn = yes ]]; then
      echo "found in config"
      grep -q '^MouseIn' $configfile && sed -i 's/^MouseIn.*/MouseIn=no/' $configfile || echo 'MouseIn=no' >> $configfile
		  /home/pi/scripts/disable_cursor &
      echo "Mouse removed"
    fi
	fi
fi

if [[ ! $(find /dev/disk/by-id -lname "*sd*") = *usb* ]]; then
  name=${name//"'"}
  if [[ $device = empty  ]]; then
    echo "run"

  else
    sudo umount "/media/pi/$name"
    sudo rm -rf "/media/pi/$name"
    grep -q "^name" $configfile && sed -i "s/^name.*/name=empty/" $configfile || echo "name=empty" >> $configfile
    grep -q "^device" $configfile && sed -i "s/^device.*/device=empty/" $configfile || echo "device=empty" >> $configfile
    echo "completed"
  fi
fi
