#!/bin/bash

configfile=/home/pi/scripts/config.cfg
if [ ! -f $configfile ]; then
  echo "making config file"
  touch $configfile
  echo "MouseIn=no" >> $configfile
fi

source $configfile

if [[ $(lsusb | grep -i 'Mouse'| tr "A-Z" "a-z") = *mouse* ]]; then
  echo "device found"
	if ! (grep -q "#xserver-command=X -nocursor" /etc/lightdm/lightdm.conf); then
    echo "line found"
    if [[ $MouseIn = no ]]; then
      echo "mouse not in"
      grep -q '^MouseIn' $configfile && sed -i 's/^MouseIn.*/MouseIn=yes/' $configfile || echo 'MouseIn=yes' >> $configfile
		  /home/pi/scripts/enable_cursor &
    fi
	fi
fi

