#!/bin/bash

###
#
# This script purges dhcpcd as it conflicts with setting
# a static IP address trough NetworkManager. For image v1.0
# the purge is executed immediately. For v1.1, the script
# makes root writable, reboots, purges dhcpcd, makes root ro again
# and reboots again. For >= v1.2, does nothing.
#
###

source_nm_state_dir="/var/lib/NetworkManager"
target_nm_state_dir="/home/etc/NetworkManager/state"
autostart="/home/pi/.config/openbox/autostart"
imageinfo="/boot/lpfrgpi.json"

do_start()
{
    if  ! dhcpcd_installed && state_writable ; then
        echo "Dhcpcd not found. State already writable. Nothing to do."
        exit 0
    elif [ ! -f "$imageinfo" ]; then
        # No image info, we are < v1.1
        echo "Image version < 1.1, going to purge dhcpcd"
        do_disable_dhcpcd
		echo "Purging done. Moving NM state folder..."
		do_move_nm_state
        echo "Folder moved. Please reboot."
        exit 3
    elif grep -q "\"image_version\"\: \"1.1.0\"" "$imageinfo"; then
        # V1.1
        echo "Image version == 1.1, going to purge dhcpcd on the next reboot"
        do_install
        echo "Installation done. Please reboot."
        exit 3
    else
        echo "Image version > 1.1. Nothing to do."
        exit 0
    fi
}

do_install() {
    # Ensures script runs on next startup
    if ! grep -i -q "disable_dhcpcd" "$autostart"; then
        # Makes root read-writable again on next reboot
        sudo sed -i "s@boot=overlay @@" /boot/cmdline.txt
        sudo sed -i "s@root_readonly=\"yes\"@root_readonly=\"no\"@" /boot/octopi.txt

        # Append script to autostart file
        sudo sed -i '1 i\/home/pi/scripts/disable_dhcpcd run' "$autostart"

        echo "Script installed."
    else
        echo "Script is already installed."
    fi
}

do_uninstall() {
    # Don't run script on next boot anymore
    sudo sed -i '/disable_dhcpcd/d' "$autostart"

    # Makes root read-writable again on next reboot
    sudo sed -i '1s@^@boot=overlay @' /boot/cmdline.txt
    sudo sed -i "s@root_readonly=\"no\"@root_readonly=\"yes\"@" /boot/octopi.txt

    echo "Script uninstalled"
}

do_move_nm_state() {
	if ! state_writable ; then
		sudo service NetworkManager stop
		sudo mv "$source_nm_state_dir" "$target_nm_state_dir"
		sudo ln -s "$target_nm_state_dir" "$source_nm_state_dir"
		echo "State folder moved."
	else
		echo "State folder was already writable."
	fi
}

do_disable_dhcpcd() {
	if dhcpcd_installed ; then
		sudo apt-get -y purge dhcpcd5
		echo "dhcpcd purged."
	else
		echo "dhcpcd was already disabled"
	fi
}

dhcpcd_installed() {
	dpkg -l | grep -q "dhcpcd"
}

state_writable() {
	if [[ -L "$source_nm_state_dir" ]] && [[ -d "$target_nm_state_dir" ]]; then
		return 0
	else
		return 1
	fi
}

key="$1"

case $key in
    "run")
    do_disable_dhcpcd
	do_move_nm_state
    do_uninstall
    sudo reboot
    ;;

    *)
    do_start
    ;;
esac
